"""旧库迁移时一次性写入 SQLite 的权限目录种子；运行时不读取此文件。"""

# 历史权限升级时一次性写入中文名称，管理员随后可独立调整展示文案。
DEFAULT_PERMISSION_LABELS = {"users.manage": "管理用户与角色", "catalog.manage": "管理基础资料",
              "inventory.view": "查看库存与入库单", "receipt.create": "创建入库单",
              "receipt.post": "确认入库", "receipt.reverse": "冲销已确认入库", "warehouse.manage": "管理仓库",
              "transfer.create": "创建调拨单", "transfer.post": "确认调拨",
              "transfer.reverse": "冲销已确认调拨单",
              "purchase_order.create": "创建采购订单", "purchase_order.confirm": "确认采购订单",
              "purchase_order.cancel": "取消采购订单",
              "stocktake.create": "创建盘点单", "stocktake.post": "确认盘点单",
              "stocktake.cancel": "取消盘点单", "stocktake.reverse": "冲销已确认盘点单", "sales.view": "查看销售单据",
              "customer.manage": "管理客户", "sales_order.create": "创建销售订单",
              "sales_order.confirm": "确认销售订单", "sales_order.cancel": "取消销售订单",
              "shipment.create": "创建出库单", "shipment.post": "确认出库",
              "shipment.cancel": "取消出库草稿", "shipment.reverse": "冲销已确认出库",
              "sales_return.create": "创建销售退货单",
              "sales_return.post": "确认销售退货", "sales_return.cancel": "取消销售退货草稿",
              "sales_return.reverse": "冲销已确认销售退货",
              "bom.activate": "启用生产物料清单版本", "bom.cancel": "取消生产物料清单草稿",
              "bom.create": "创建生产物料清单", "bom.retire": "停用生产物料清单版本",
              "finance.record": "登记收付款", "finance.reverse": "冲销收付款",
              "finance.view": "查看应收应付",
              "material_issue.cancel": "取消生产领料单", "material_issue.create": "创建生产领料单",
              "material_issue.post": "确认生产领料", "material_issue.reverse": "冲销已确认生产领料",
              "material_return.cancel": "取消生产退料单", "material_return.create": "创建生产退料单",
              "material_return.post": "确认生产退料", "material_return.reverse": "冲销已确认生产退料",
              "production.view": "查看生产业务",
              "production_completion.cancel": "取消完工报工单",
              "production_completion.create": "创建完工报工单",
              "production_completion.inspect": "检验完工报工",
              "production_completion.post": "确认完工入库",
              "production_completion.reverse": "冲销已确认完工入库",
              "production_cost.record": "登记生产成本",
              "production_cost.reverse": "冲销生产成本记录",
              "production_cost.view": "查看生产成本",
              "purchase_return.cancel": "取消采购退货单",
              "purchase_return.create": "创建采购退货单",
              "purchase_return.post": "确认采购退货",
              "purchase_return.reverse": "冲销已确认采购退货",
              "work_order.cancel": "取消生产工单",
              "work_order.create": "创建生产工单",
              "work_order.release": "下达生产工单"}


# 迁移时建立模块与单据节点；运行时的中文名称和所属关系均以数据库为准。
PERMISSION_GROUP_PATHS = {
    "users": (("system", "系统管理"), ("users", "用户与角色")),
    "catalog": (("catalog", "基础资料"), ("materials", "物料与供应商")),
    "inventory": (("warehouse", "仓库管理"), ("inventory", "库存查看")),
    "warehouse": (("warehouse", "仓库管理"), ("warehouses", "仓库资料")),
    "receipt": (("warehouse", "仓库管理"), ("receipt", "入库单")),
    "shipment": (("warehouse", "仓库管理"), ("shipment", "出库单")),
    "transfer": (("warehouse", "仓库管理"), ("transfer", "调拨单")),
    "stocktake": (("warehouse", "仓库管理"), ("stocktake", "盘点单")),
    "purchase_order": (("purchase", "采购管理"), ("purchase_order", "采购订单")),
    "purchase_return": (("purchase", "采购管理"), ("purchase_return", "采购退货单")),
    "sales": (("sales", "销售管理"), ("sales", "销售单据查看")),
    "customer": (("sales", "销售管理"), ("customer", "客户资料")),
    "sales_order": (("sales", "销售管理"), ("sales_order", "销售订单")),
    "sales_return": (("sales", "销售管理"), ("sales_return", "销售退货单")),
    "finance": (("finance", "财务管理"), ("finance", "应收应付")),
    "production": (("production", "生产管理"), ("production", "生产业务查看")),
    "bom": (("production", "生产管理"), ("bom", "生产物料清单")),
    "work_order": (("production", "生产管理"), ("work_order", "生产工单")),
    "material_issue": (("production", "生产管理"), ("material_issue", "生产领料单")),
    "material_return": (("production", "生产管理"), ("material_return", "生产退料单")),
    "production_completion": (("production", "生产管理"), ("production_completion", "完工报工单")),
    "production_cost": (("production", "生产管理"), ("production_cost", "生产成本")),
}
