"""单据类型白名单；前缀固定，客户端不能自定义类型或参与分配流水。"""

# 模型名、数据库表名、拼音前缀、英文前缀共同维护，迁移与业务生成复用同一清单。
DOCUMENT_TYPES = (
    ('PurchaseRequest', 'purchase_requests', 'CGSQ', 'PR'),
    ('PurchaseOrder', 'purchase_orders', 'CGDD', 'PO'),
    ('PurchaseGoodsReceipt', 'purchase_goods_receipts', 'CGSH', 'GR'),
    ('Receipt', 'receipts', 'CGRK', 'PIN'),
    ('PurchaseReturn', 'purchase_returns', 'CGTH', 'PRT'),
    ('WarehouseInbound', 'warehouse_inbounds', 'QTRK', 'OIN'),
    ('WarehouseOutbound', 'warehouse_outbounds', 'CKD', 'OUT'),
    ('Transfer', 'transfers', 'DBD', 'TRF'),
    ('Stocktake', 'stocktakes', 'PDD', 'STK'),
    ('StockAdjustment', 'stock_adjustments', 'TZD', 'ADJ'),
    ('CrmQuote', 'crm_quotes', 'BJD', 'QUO'),
    ('SalesOrder', 'sales_orders', 'XSDD', 'SO'),
    ('Shipment', 'shipments', 'XSCK', 'SHP'),
    ('SalesReturn', 'sales_returns', 'XSTH', 'SRT'),
    ('AfterSalesCase', 'after_sales_cases', 'SHD', 'ASC'),
    ('WorkOrder', 'work_orders', 'SCGD', 'WO'),
    ('MaterialIssue', 'material_issues', 'SCLL', 'MI'),
    ('MaterialReturn', 'material_returns', 'SCTL', 'MR'),
    ('ProductionCompletion', 'production_completions', 'WGD', 'CMP'),
    ('QualityDisposition', 'quality_dispositions', 'BHGCZ', 'QDS'),
    ('MrpPlan', 'mrp_plans', 'WLXQ', 'MRP'),
    ('ProductionCostSettlement', 'production_cost_settlements', 'CBJS', 'PCS'),
    ('MaintenanceJob', 'maintenance_jobs', 'WHGD', 'MNT'),
    ('Journal', 'journals', 'PZ', 'JV'),
    ('OpeningBalance', 'opening_balances', 'ZZQC', 'GOB'),
    ('SubledgerOpening', 'subledger_openings', 'FHQC', 'SLO'),
    ('PaymentRecord', 'payment_records', 'SKFK', 'PAY'),
    ('SubledgerPayment', 'subledger_payments', 'LSSKFK', 'SLP'),
    ('OrderSettlementTransfer', 'order_settlement_transfers', 'DDHX', 'OSL'),
)
